In [39]:
import pandas as pd

#경로 작성 방법 파일/파일/파일.../
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [16]:
import pandas as pd

#경로 작성 방법 파일/파일/파일.../
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding="utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140

In [17]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try:
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except:
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed":"int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [40]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2522 entries, 0 to 2521
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FIPS            2175 non-null   float64
 1   Admin2          2221 non-null   object
 2   Province_State  2338 non-null   object
 3   Country_Region  2522 non-null   object
 4   Last_Update     2522 non-null   object
 5   Lat             2518 non-null   float64
 6   Long_           2518 non-null   float64
 7   Confirmed       2522 non-null   int64
 8   Deaths          2522 non-null   int64
 9   Recovered       2522 non-null   int64
 10  Active          2522 non-null   int64
 11  Combined_Key    2522 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 236.6+ KB

In [41]:
country_info = pd.read_csv("./COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv")

country_info.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.94990,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.03390,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.50630,1.521800,Andorra,77265.0

In [42]:
import pandas as pd

test_df = pd.merge(doc, country_info, on="Country_Region", how="left")

In [45]:
test_df

,FIPS_x,Admin2_x,Province_State_x,Country_Region,Last_Update,Lat_x,Long__x,Confirmed,Deaths,Recovered,...,iso2,iso3,code3,FIPS_y,Admin2_y,Province_State_y,Lat_y,Long__y,Combined_Key_y,Population
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,US,USA,840.0,NaN,NaN,NaN,40.000000,-100.000000,US,329466283.0
1,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,AS,ASM,16.0,60.0,NaN,American Samoa,-14.271000,-170.132000,"American Samoa, US",55641.0
2,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,GU,GUM,316.0,66.0,NaN,Guam,13.444300,144.793700,"Guam, US",164229.0
3,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,MP,MNP,580.0,69.0,NaN,Northern Mariana Islands,15.097900,145.673900,"Northern Mariana Islands, US",55144.0
4,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,VI,VIR,850.0,78.0,NaN,Virgin Islands,18.335800,-64.896300,"Virgin Islands, US",107268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7591770,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,MS,MSR,500.0,NaN,NaN,Montserrat,16.742498,-62.187366,"Montserrat, United Kingdom",4999.0
7591771,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,TC,TCA,796.0,NaN,NaN,Turks and Caicos Islands,21.694000,-71.797900,"Turks and Caicos Islands, United Kingdom",38718.0
7591772,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,PN,PCN,612.0,NaN,NaN,Pitcairn Islands,-24.376800,-128.324200,"Pitcairn Islands, United Kingdom",67.0
7591773,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,AI,AIA,660.0,NaN,NaN,Anguilla,18.220600,-63.068600,"Anguilla, United Kingdom",15002.0
7591774,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,SH,SHN,654.0,NaN,NaN,"Saint Helena, Ascension and Tristan da Cunha",-7.946700,-14.355900,"Saint Helena, Ascension and Tristan da Cunha, ...",5661.0

In [46]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7591775 entries, 0 to 7591774
Data columns (total 23 columns):
 #   Column            Dtype
---  ------            -----
 0   FIPS_x            float64
 1   Admin2_x          object
 2   Province_State_x  object
 3   Country_Region    object
 4   Last_Update       object
 5   Lat_x             float64
 6   Long__x           float64
 7   Confirmed         int64
 8   Deaths            int64
 9   Recovered         int64
 10  Active            int64
 11  Combined_Key_x    object
 12  UID               int64
 13  iso2              object
 14  iso3              object
 15  code3             float64
 16  FIPS_y            float64
 17  Admin2_y          object
 18  Province_State_y  object
 19  Lat_y             float64
 20  Long__y           float64
 21  Combined_Key_y    object
 22  Population        float64
dtypes: float64(8), int64(5), object(10)
memory usage: 1.3+ GB

In [50]:
test_df.isnull().sum()

FIPS_x              197269
Admin2_x             27049
Province_State_x       804
Country_Region           0
Last_Update              0
Lat_x                 3488
Long__x               3488
Confirmed                0
Deaths                   0
Recovered                0
Active                   0
Combined_Key_x           0
UID                      0
iso2                     5
iso3                     4
code3                    4
FIPS_y               52223
Admin2_y            143571
Province_State_y      2522
Lat_y               265276
Long__y             265276
Combined_Key_y           0
Population          265279
dtype: int64

In [54]:
nan_rows = test_df[test_df["iso2"].isnull()]
nan_rows

,FIPS_x,Admin2_x,Province_State_x,Country_Region,Last_Update,Lat_x,Long__x,Confirmed,Deaths,Recovered,...,iso2,iso3,code3,FIPS_y,Admin2_y,Province_State_y,Lat_y,Long__y,Combined_Key_y,Population
7590572,NaN,NaN,NaN,Diamond Princess,2020-04-01 21:58:34,0.0000,0.0000,712,11,603,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diamond Princess,NaN
7590762,NaN,NaN,NaN,MS Zaandam,2020-04-01 21:58:34,0.0000,0.0000,9,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MS Zaandam,NaN
7590854,NaN,NaN,NaN,Namibia,2020-04-01 21:58:34,-22.9576,18.4904,14,0,2,...,NaN,NAM,516.0,NaN,NaN,NaN,-22.9576,18.4904,Namibia,2540916.0
7591290,NaN,NaN,NaN,Summer Olympics 2020,2020-04-01 21:58:49,35.6491,139.7737,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,35.6491,139.7737,Summer Olympics 2020,NaN
7591598,NaN,NaN,NaN,Winter Olympics 2022,2020-04-01 21:58:49,39.9042,116.4074,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,39.9042,116.4074,Winter Olympics 2022,NaN

In [ ]:
selected_colums =["이름", "수학", "국어"]
df = df[selected_colums]